"""Add date_created to ShortLink model

Revision ID: 244ab6d677e7
Revises: 
Create Date: 2025-10-24 22:07:12.456769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244ab6d677e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_date_posted'), ['date_posted'], unique=False)

    with op.batch_alter_table('short_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_short_link_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_short_link_short_url'), ['short_url'], unique=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_date_posted'), ['date_posted'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_date_posted'))
        batch_op.drop_index(batch_op.f('ix_task_completed'))

    with op.batch_alter_table('short_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_short_link_short_url'))
        batch_op.drop_index(batch_op.f('ix_short_link_date_created'))
        batch_op.drop_column('date_created')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_date_posted'))

    # ### end Alembic commands ###
